`define ANI_RANDOM_SEED 1
`include "/motion_bmc/bmc_asic/std_cell/pll/S40NLLPLLGS_ZP1500_V1.6.5.v"
`include "/motion_bmc/bmc_asic/std_cell/pad/SPC40NLLD2RNP_OV3_V1p1.v"
`include "/motion_bmc/bmc_source/common/bmc_common_define.h"
`include "/motion_bmc/bmc_source/common/common_manifest.v"
//`include "/motion_bmc/bmc_source/top/bmc_all_manifest.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/IIC400.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/APB2OPB.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/APB_arb.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/APB_DMA.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/IIC_ctrl.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/OPB_arb.v"
`include "/home/xuehao/UVMP/I2CTB/i2cU/i2c/source/I2C_APB_top.v"
